# cf) https://docs.github.com/ja/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: friday

  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/*"
    schedule:
      interval: "weekly"
      day: friday
    groups:
      aws-sdk-group:
        patterns:
          - "@aws-sdk/*"
      vitest-group:
        patterns:
          - "vitest"
          - "@vitest/*"
